### ISSUE TITLE
Please take down this repository

### ISSUE THREAD

**Issue by ItziSpyder** [L0rqx/ClickCrystals#1]
In [MarlowYT Discord](https://discord.gg/marlow) you posted a cursedforge link claiming this mod is yours. Unless you redirect your link to my [Modrinth](https://modrinth.com/mod/clickcrystals) please take down this repository and the project on cursedforge. 

The fact that your only commit in this repository is the initial one and right off the bat it is already version 0.6.5 tells everyone it's a fake. If you were only trying to help advertise my mod, I thank you for that. 

Unfortunately, I'm going to have to ask you to take down this repository and the project you created on cursedforge and take back any claims you may have made. The real repository is at [ClickCrystals Github](https://discord.gg/marlow)

If you do wish to contribute to this project feel free to instead of cloning directly, fork my project and submit a pull request for review at any time, and I will get to you as soon as possible.

Have a nice day.

**Comment by L0rqx** [comment]
Bro are you tripping? I never posted anything in any discord?
